name: SecurityPipeline

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']
  workflow_dispatch:

jobs:
  secret-scan:
    name: Gitleaks-proxy
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: 🔐 Gitleaks Secret Scan & DefectDojo Upload
        uses: PoorneshORG/gitleaks-scan@dojoaction
        continue-on-error: true
        with:
          dojo-url: ${{ secrets.DEFECTDOJO_URL }}
          dojo-api-key: ${{ secrets.DEFECTDOJO_API_KEY }}
          product-name: DevSecOps
          report-file: gitleaks-report.json
          repo-name: ${{ github.repository }}
          test-title: ${{ github.ref_name }}-${{ github.sha }}
